# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "mpt3sas" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "defaults" "size=2G" "mode=755" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/68D5-F3CC";
    fsType = "vfat";
  };

  fileSystems."/boot-fallback" = {
    device = "/dev/disk/by-uuid/68F4-D4F4";
    fsType = "vfat";
  };

  fileSystems."/nix" = {
    device = "zroot-0a5dd4/local/nix";
    fsType = "zfs";
  };

  fileSystems."/local/storage" = {
    device = "zroot-0a5dd4/local/storage";
    fsType = "zfs";
  };

  fileSystems."/persist" = {
    device = "zroot-0a5dd4/safe/persist";
    fsType = "zfs";
  };

  fileSystems."/storage" = {
    device = "zpool-fnazxg/safe/storage";
    fsType = "zfs";
  };

  fileSystems."/var/lib/tailscale" = {
    device = "/persist/var/lib/tailscale";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/etc/postfix.local" = {
    device = "/persist/etc/postfix.local";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/var/cache/private/sanoid" = {
    device = "/persist/var/cache/private/sanoid";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/var/cache/mlocate" = {
    device = "/persist/var/cache/mlocate";
    fsType = "none";
    options = [ "bind" ];
  };

  # SMB + Time Machine
  fileSystems."/backup/lap-ca-nik-01/time-machine" = {
    device = "zpool-fnazxg/backup/lap-ca-nik-01/time-machine";
    fsType = "zfs";
  };
  fileSystems."/var/lib/samba" = {
    device = "/persist/var/lib/samba";
    fsType = "none";
    options = [ "bind" ];
  };
  fileSystems."/var/cache/samba" = {
    device = "/persist/var/cache/samba";
    fsType = "none";
    options = [ "bind" ];
  };

  # SMB guest share
  fileSystems."/guest" =
    {
      device = "zpool-fnazxg/safe/guest";
      fsType = "zfs";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
